= Document Title MY
:doctype: book
:title-page:
:!chapter-signifier:
:name-prog: Руководство
:toc: macro
// :doctitle: any
// :pdf-page-layout: landscape
// [.metadata]
// {author} -- version {revnumber}, {revdate}

toc::[]

== Приложение 1 

// [.my-bold-title]
Сводная информация государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам производителям товаров, работ, услуг, подсистемы управления расходами государственной интегрированной 


. о фактической трудоемкости работ 
. по сопровождению модуля организации предоставления в электронном виде мер 
.. государственной финансовой 
.. поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам 
... государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам 
... производителям товаров, работ, услуг, подсистемы управления расходами государственной интегрированной 
.. информационной системы 
.. управления общественными финансами «Электронный бюджет», 
. оператором которых является Министерство 
. финансов Российской Федерации 

//--

. о фактической трудоемкости работ 
. по сопровождению модуля организации предоставления в электронном виде мер 
.. государственной финансовой 
.. поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам 
... государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам 
... производителям товаров, работ, услуг, подсистемы управления расходами государственной интегрированной 
.. информационной системы 
.. управления общественными финансами «Электронный бюджет», 
. оператором которых является Министерство 
. финансов Российской Федерации 


== Приложение 2

Сводная информация государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам производителям товаров, работ, услуг, подсистемы управления расходами государственной интегрированной 

* о фактической трудоемкости 
* работ по сопровождению модуля организации предоставления в электронном виде мер 
** государственной финансовой 
** поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам
*** производителям товаров, работ, услуг, подсистемы управления расходами государственной интегрированной 
*** производителям товаров, работ, 
** услуг, подсистемы управления расходами государственной интегрированной 
** информационной системы управления общественными финансами «Электронный бюджет», оператором которых является
* Министерство финансов 
* Российской Федерации +
