include::common/contract.adoc[]
:docinfo: shared
:!chapter-signifier:
:!section-refsig:
:figure-caption!:
:imagesdir: ../images
:table-caption!: 
:section-refsig: разделе
:toc: macro
:toc-title: Содержание 
:name1_dokument: Описание информационного обеспечения
:name5_dokument: 
:sectnumlevels: 7
// Кол-во страниц соответствует пдф и версия
:version: 1
:page_all: 22
:code: П5
:toclevels: 4
:ramka: 1
:plan:
// :title-page: — это директива, которая создает отдельную страницу титульного листа для документа.

//Служеб. настрока титульника. Менять год здесь
include::tables/titul_doc.adoc[]

<<<<
toc::[]

<<<<
:!sectnums: 
== Перечень терминов и сокращений

[cols="2,8", options="header"]
|===
^| Термин/сокращение  ^| Определение/расшифровка
| ВПД                         | Внешняя поставка данных
| ГиРБО                       | Государственный информационный ресурс бухгалтерской отчетности
| ГИС                         | Государственная информационная система 
| ГРБС                        | Главный распорядитель средств федерального бюджета 
| ЕСНСИ                       | Единая система нормативной справочной информации 
| ИС                          | Информационная система   
| Модуль                      | Модуль организации предоставления в электронном виде мер государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам – производителям товаров, работ, услуг в Подсистеме управления расходами государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет»
| ПИАО                        | Подсистема информационно-аналитического обеспечения  
| РАПФ                        | Государственный реестр аккредитованных филиалов, представительств иностранных юридических лиц  
| Система «Электронный бюджет | Государственная интегрированная информационная система управления общественными финансами «Электронный бюджет»  
| СМЭВ                        | Система межведомственного электронного взаимодействия  
| Справочник                  | Перечень, содержащий краткие сведения субъектов окружения системы, сгруппированные по какому-либо признаку    
| ФК                          | Федеральное казначейство 
| ФНС                         | Федеральная налоговая служба     
| ФССП                        | Федеральная служба судебных приставов   
|===

<<<<
// Основная часть ********************
:sectnums: 
== Состав информационного обеспечения

:num_t: {counter:table-number}
Информационное обеспечение Модуля состоит из взаимосвязанных компонентов, обеспечивающих его работу и взаимодействие с пользователями, а также внешними системами. Состав информационного обеспечения для Модуля представлен в <<id_t_{num_t}, Таблице {num_t}>>. 

[.landscape]
<<<<
[%breakable]
[#id_t_{num_t}]
.Таблица {num_t}. Состав информационного обеспечения
include::tables/t_inf_support.adoc[tag=inf_dan]

[.portrait]
<<<<

[%breakable]
=== Информационные потоки

:num_t: {counter:table-number}
Модуль взаимодействует с различными узлами посредством интеграционных потоков данных, которые обеспечивают обмен информацией. Интеграционные потоки организуются с использованием RestAPI, gRPC, СМЭВ и других протоколов, образуя как входящие, так и исходящие потоки между Модулем и постоянными участниками интеграционных взаимодействий. Обмен данными осуществляется через централизованную шину данных с использованием брокера RabbitMQ, который управляет передачей сообщений между сервисами.  
// tag::inf_vzaim_extern_system[]
Информационное взаимодействие с внешними системами представлено в <<id_t_{num_t}, Таблице {num_t}>>. 

[.landscape]
<<<<
[%breakable]
[#id_t_{num_t}]
.Таблица {num_t}. Информационное взаимодействие с внешними системами
include::tables/t_inf_support.adoc[tag=inf_thread]

[.portrait]
<<<<
// end::inf_vzaim_extern_system[]

Взаимодействие с пользователями модуля осуществляется через механизм веб-интерфейса, обеспечивающий полный доступ к функциональным возможностям системы. В зависимости от уровня предоставленных прав пользователи могут вводить новые данные, сохранять существующую информацию, просматривать различные документы и отчеты, а также загружать необходимые данные для дальнейшей обработки или анализа.

=== Информационные модели

Информационные модели Модуля определяют структуру и формат данных, обеспечивая корректность их обработки и обмена. В Модуле применяются:

* JSON-схемы: для описания данных, передаваемых и получаемых через API, обеспечивая корректный формат данных при интеграции с внешними системами;
* XSD-схемы: для структурирования данных, обмениваемых через СМЭВ и FTP, гарантируя соответствие данных стандартам обмена;
* схемы баз данных: определяют структуру таблиц и взаимосвязи в реляционных базах данных Модуля, обеспечивая эффективное управление и целостность данных.

=== Информационная инфраструктура

Информационная инфраструктура Модуля обеспечивает его функционирование, хранение данных и взаимодействие с пользователями и внешними системами. Она включает:

* серверы приложений: для обработки запросов пользователей, выполнения бизнес-логики и взаимодействия с базами данных;
* серверы баз данных: с развернутыми реляционными СУБД, обеспечивают хранение и управление данными Модуля;
* сетевое оборудование: для взаимодействия между компонентами инфраструктуры, связи с внешними системами и пользователями;
* средства информационной безопасности: программные и аппаратные решения для защиты данных Модуля от несанкционированного доступа и действий.

== Организация информационного обеспечения
=== Принципы организации информационного обеспечения Модуля

Основными принципами организации информационного обеспечения в Модуле являются:

* управление информационным обеспечением с использованием метаинформации; 
* обеспечение информационного взаимодействия с внешними информационными системами на основе определяемых форматов обмена;
* контроль целостности и полноты данных на всех этапах жизненного цикла;
* логирование операций.

=== Описание организации баз данных и массивов информации 

Состав и структура баз данных, используемых Модулем, описана в документе «Описание организации информационной базы». 

=== Описание решений, обеспечивающих интеграцию в системе «Электронный бюджет»

Информационная совместимость в системе «Электронный бюджет» достигается за счет использования протокола gRPC при взаимодействии с подсистемой управления расходами и протокола FTP при взаимодействии с ПИАО. 

Система удалённого вызова процедур (RPC) с открытым исходным кодом (Remote Procedure Calls – gRPC). gRPC предоставляет такие функции как аутентификация, двунаправленная потоковая передача и управление потоком, блокирующие или неблокирующие привязки, а также отмена и тайм-ауты. Генерирует кроссплатформенные привязки клиента и сервера для многих языков программирования. Используется для подключения служб в микросервисных архитектурах, а также мобильных устройств и браузерных клиентов к серверным службам.

Протокол FTP (англ. File Transfer Protocol) построен на архитектуре «клиент-сервер» и использует разные сетевые соединения для передачи команд и данных между клиентом и сервером.

=== Описание решений, обеспечивающих информационное взаимодействие с другими ИС

Организация сбора и передачи информации при взаимодействии с внешними ИС осуществляется посредством:

* системы межведомственного электронного взаимодействия (СМЭВ);
* интерфейс прикладного программирования (Rest API);
* парсинга сайтов (РАФП, Рособрнадзор, ФССП). 

==== Система межведомственного электронного взаимодействия

СМЭВ позволяет федеральным, региональным и местным органам власти, кредитным организациям (банкам), внебюджетным фондам, и прочим участникам СМЭВ обмениваться данными, необходимыми для оказания государственных услуг гражданам и организациям, в электронном виде.

==== Интерфейс прикладного программирования

Интерфейс прикладного программирования (API – application programming interface), набор методов, классов, библиотек, функций, обеспечивающих взаимодействие программ между собой и представляет собой промежуточный слой между двумя приложениями:

. Очередной скрипт, который выполняет функцию REST запросов. 
. Скрипт обращается к одному из методов получения информации и команды с сайта https://vpd.nalog.gov.ru/.
. Посылается запрос на получение авторизационного токена. 
. Кодируется этот токен в base64 (требование системы ФНС). 
. Используется полученный токен и подставляется в GET-запросы для получения информации: 
.. данные по ЕГРЮЛ/ЕГРИП;
.. различные задолженности;
.. система «Прозрачный бизнес».
. Полученные данные выводятся в профиль. 

==== Парсинг сайтов

Парсинг – автоматизированный сбор неструктурированной информации на различных сайтах, ее преобразование и передача в структурированном виде. 
Для парсинга используется скрипт, который выполняет определенный функционал: 

. С определенной периодичностью (раз в неделю) обращается к сайту, на котором содержится нужная информация, например сайт ФССП или Рособрнадзора. С сайта из определенного поля скачивается файл с данными в формате CSV. 
. Далее скаченный файл интегрируется в Модуль, а точнее в созданную под него БД. 
. Далее осуществляется стандартная система запроса к БД. По ИНН заявителя производится поиск значения в таблице, созданной на основании CSV файла. 

Требуемое значение определяется в зависимости от ИС. В случае с сайтом Рособрнадзора: по ИНН извлекается значение из столбца, содержащего данные по аккредитации. Если ИНН в таблице не найден, атрибуты данных Accreditations в профиле не присваиваются. 

В случае с сайтом ФССП: по ИНН осуществляется поиск в столбце, содержащего данные с задолженностью, если ИНН отсутствует, атрибуты задолженности в профиле присваиваются False. 

==== Протокол передачи файлов по сети

Протокол передачи файлов по сети – FTP, используется для отправки данных по отборам, заявкам, победителям в ФК.

=== Описание принятых видов и методов контроля в маршрутах обработки данных

В Модуле приняты следующие виды контроля данных:

* форматный контроль данных;
* контроль полноты данных;
* логический контроль данных;
* контроль ссылочной целостности данных;
* контроль на дублирование информационных объектов;
* контроль целостности электронных документов, защищенных ЭП. 

Форматный контроль данных осуществляется на основе метаинформации для каждого формуляра и включает проверку значений на соответствие типам данных, размерности и маске поля. Полнота данных контролируется по наличию значений в атрибутах формулярах и полях записей базы данных, определенных в метаинформации, как обязательные к заполнению, в том числе и обязательные при выполнении логических условий. Правила логического контроля данных указываются при проектировании жизненного цикла формуляра и реализуются в библиотеке повторно используемых функций. 

Контроль ссылочной целостности данных обеспечивается штатными средствами системы управления базами данных.

Контроль на дублирование информационных объектов осуществляется с помощью методов предварительной проверки на повторение метаинформации обязательных полей перед добавлением или изменением информации в базе данных.

Контроль целостности электронных документов, защищенных ЭП, производится программными средствами Модуля, реализующих управление жизненным циклом формуляра, и включает запрет на редактирование подписанных документов.

== Атрибутный состав информации

Наборы данных и их обозначение приведены в документе «Описание организации информационной базы».

== Построение системы классификации и кодирования

В Модуле используется существующая система классификации и кодирования. В рамках настоящего проекта изменения в систему классификации и кодирования не вносились.


<<<<
include::tables/t_podpis.adoc[]

<<<<
include::tables/t_list_change.adoc[]
