include::common/contract.adoc[]
:docinfo: shared
:!chapter-signifier:
:!section-refsig:
:table-caption!: 
:section-refsig: разделе
:toc: macro
:toc-title: Содержание 
:name1_dokument: Отчет о результатах выполнения работ
:sectnumlevels: 7
// Кол-во страниц соответствует пдф и версия
:version: 1
:page_all: 22
:code: ТЗ-02
:toclevels: 4
:ramka: 0
:plan:
:sum_work: 20000

include::tables/titul_doc.adoc[tag=titul_start_utv]

[.my-bold-title]
{name1_dokument}

[.append-name-style]
по адаптационному сопровождению подсистем, (компонент, модулей) государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет» в части модуля организации предоставления в электронном виде мер государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам – производителям товаров, работ, услуг Министерства финансов Российской Федерации

{nbsp}

[.append-name-style]
Договор {сontract_number} ({stage} этап) +     
(Государственный контракт {state_сontract}) +
Версия 0026.0{stage}.{code}.0{version} +

include::tables/titul_doc.adoc[tag=titul_end_utv]

<<<<
toc::[]
<<<<

// :!t_row:

include::common/rms_report.adoc[tag=report_intro]

Работы, предусмотренные требованиями Договора, проводились по следующим направлениям:

в соответствии с требованиями, изложенными в п. 3.1 «Требования к составу и функционированию СТП» Технического задания Договора, обеспечены мероприятия по настройке защищенного доступа к проектным репозиториям и программному обеспечению (ПО), необходимым для сопровождения СТП, сбору и защите информации о функционировании ИТ-инфраструктуры, соблюдению требований информационной безопасности и законодательства РФ, обеспечению конфиденциальности данных, а также передаче всех результатов работ, включая исключительные права на модифицированное прикладное программное обеспечение (далее ППО);

в соответствии с требованиями, изложенными в п. 3.2 «Требования к управлению изменениями» Технического задания Договора, разработан план проведения работ по внесению изменений в ППО;

в соответствии с требованиями, изложенными в п. 3.3 «Требования к работе по проведению нагрузочного тестирования» Технического задания Договора, проведено нагрузочное тестирование с целью оценки соответствия текущего состояния ППО целевым показателям назначения и технорабочей документации;

в соответствии с требованиями, изложенными в п. 3.4 «Требования к работе по проведению функционального тестирования» Технического задания Договора, проведено функциональное тестирование с целью оценки соответствия текущего состояния ППО целевым показателям назначения и технорабочей документации;

в соответствии с требованиями, изложенными в п. 3.5 «Требования к работе по управлению проблемами и рисками» Технического задания Договора, выполнены мероприятия по:

* выявлению и прогнозированию проблем на основе анализа инцидентов;
* диагностике проблем;
* предоставлению временного решения для устранения проблем;
* предоставлению постоянного решения для устранения проблем;
* информированию Заказчика о ходе устранения проблем;
* мониторингу актуальности решения проблемы;
* передаче описания проблем Заказчику;

в соответствии с требованиями, изложенными в п. 3.6.1 «Адаптация (модификация) ППО» Технического задания Договора, выполнены работы по адаптации (модификации) ППО;
 
в соответствии с требованиями, изложенными в п. 3.6.2 «Поддержка в актуальном состоянии информационного обеспечения ГИС Минфина» Технического задания Договора, обеспечена поддержка в актуальном состоянии форм документов, классификаторов, нормативной базы и реализованных решений;
 
в соответствии с требованиями, изложенными в разделе 4 «Требования к составу и содержанию документов» Технического задания Договора, подготовлена отчетная документация, технорабочая и эксплуатационная документация на ППО в соответствии с требованиями Технического задания к Договору.

:sectnums: 
== Выполнение требований к составу и функционированию СТП (п. 3.1. Технического задания Договора)

В соответствии с требованиями п. 3.1. «Требования к составу и функционированию СТП» Технического задания Договора:

настройка и обеспечение защищенного доступа к проектным репозиториям исходного кода и тестовым следам, расположенным в ИТ-инфраструктуре Минфина России, что необходимо для организации процессов разработки и сопровождения системы программного обеспечения (СТП);

организация защищенного доступа к ПО и информации, достаточной для обеспечения процессов адаптационного сопровождения системы. Весь доступ обеспечен с учетом требований информационной безопасности и ограничен в зависимости от уровня полномочий сотрудников, участвующих в выполнении работ по Договору;

сбор, обработка и защита сведений о функционировании промышленной среды ИТ-инфраструктуры, которые используются для выполнения сопровождения, а также для других целей, указанных в Договоре. В процессе работы соблюдены все необходимые меры по защите информации, в том числе предотвращены несанкционированный доступ, хищение, утрата, уничтожение, искажение и подделка данных;

соблюдение действующего законодательства Российской Федерации, в том числе законов о защите персональных данных и иных нормативных актов, регулирующих вопросы информационной безопасности. Приняты организационные и технические меры, соответствующие требованиям законодательства;

обеспечение конфиденциальности и недопущению разглашения информации третьим лицам. Исполнитель строго выполнял обязательства по недопущению передачи информации, связанной с выполнением Договора, третьим лицам, а также не использовал эту информацию в своих собственных интересах;

передача результатов выполненных работ Государственному заказчику. 

Все результаты, включая исходный код, документацию и модифицированное программное обеспечение, переданы заказчику в установленном порядке. Исключительные права на модифицированное ПО переданы Минфину России.
Сведения о фактической трудоемкости приведены в <<#application_1, Приложении 1>>.

== Выполнение требований к управлению изменениями (п. 3.2 Технического задания Договора)

В соответствии с требованиями, изложенными в 3.2 «Требования к управлению изменениями» Технического задания Договора:

обеспечено внесение изменений в ППО с учетом требований план-заданий на доработку ППО, направленных Заказчиком в адрес Исполнителя (в количестве 25 план-заданий);

по результатам внесения изменений в ППО разработано 25 отчетов о выполненной адаптации (модификации) прикладного программного обеспечения;

проведено тестирование и перенос согласованного Заказчиком изменения ППО в промышленную среду информационно-технологической инфраструктуры Минфина России;

после внесения изменений в промышленной среде информационно-технологической инфраструктуры Минфина России обеспечена идентичность конфигурации (состав программного обеспечения и его настроек) в тестовой среде информационно-технологической инфраструктуры;

при подготовке версий ППО обеспечена возможность возврата к предыдущей версии, развернутой в промышленной среде информационно-технологической инфраструктуры Минфина России.

Перечень выполненных план-заданий приведен в документе «Реестр план-заданий на доработку прикладного программного обеспечения ГИС Минфина России». Общее количество модификаций ППО по доведенным Минфином России план-заданиям составляет {num_plan_task} штук. Модификации проведены для модуля организации предоставления в электронном виде мер государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам – производителям товаров, работ, услуг. Детальные сведения о составе и трудоемкости выполненных работ в ходе модификаций работ приведены в соответствующих отчетах о выполненных адаптациях. Перечень отчетов о выполненных адаптациях приведен в документе «Ведомость машинных носителей информации», передаваемых в рамках Договора {сontract_number}». 

Дистрибутивы модифицированного ППО, актуализированные комплекты технорабочей документации, эксплуатационной документации и документации, используемой в процессах проведения испытаний в качестве результатов выполнения работ, представлены на оптических носителях данных (см. документ «Ведомость машинных носителей информации»). Сведения о фактической трудоемкости приведены в <<#application_1, Приложении 1>>.

== Выполнение требований к работе по проведению нагрузочного тестирования (п. 3.3 Технического задания Договора)

В соответствии с требованиями, изложенными в п. 3.3 «Требования к работе по проведению нагрузочного тестирования» Технического задания Договора, проведено нагрузочное тестирование подсистем (компонентов, модулей) ГИИС «Электронный бюджет» с целью оценки соответствия текущего состояния ППО целевым показателям назначения и технорабочей документации.
Нагрузочному тестированию подверглись:
модуль организации предоставления в электронном виде мер государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам – производителям товаров, работ, услуг. 
Сведения о фактической трудоемкости приведены в <<#application_1, Приложении 1>>. 

== Выполнение требований к работе по проведению функционального тестирования (п. 3.4 Технического задания Договора)
В соответствии с требованиями, изложенными в 3.4 «Требования к работе по проведению функционального тестирования» Технического задания Договора, проведено функциональное тестирование подсистем (компонентов, модулей) ГИИС «Электронный бюджет» с целью оценки соответствия текущего состояния ППО целевым показателям назначения и технорабочей документации.
Функциональному тестированию подверглись:
модуль организации предоставления в электронном виде мер государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам – производителям товаров, работ, услуг. 
Сведения о фактической трудоемкости приведены в <<#application_1, Приложении 1>>. 

== Выполнение требований к работе по управлению проблемами и рисками (п. 3.5 Технического задания Договора)

В соответствии с требованиями, изложенными в п. 3.5 «Требования к работе по управлению проблемами и рисками» Технического задания Договора выполнены следующие мероприятия:
выявление и прогнозирование проблем на основе анализа инцидентов;
диагностика проблем;
предоставление временного решения для устранения проблем;
предоставление постоянного решения для устранения проблем;
информирование Заказчика о ходе устранения проблем;
мониторинг актуальности решения проблемы;
передача описания проблем разработчику ППО и предоставление Заказчику полученного ответа разработчика.

== Выполнение работ по адаптации (модификации) ППО (п. 3.6.1. Технического задания) 

В соответствии с требованиями, изложенными в пункте 3.6.1 «Адаптация (модификация) ППО» Технического задания к Договору выполнены работы по адаптации (модификации) ППО.
Адаптация (модификация) ППО осуществлялась согласно плану проведения работ по внесению изменений в ППО, разработанного в соответствии с подразделом 3.2 «Требования к управлению изменениями» Технического задания к Договору.
В целях обеспечения соответствия ППО требованиям План-задания на доработку ППО осуществлены доработки, представленные в <<#application_1, Приложении 1>>) настоящего отчета.

Произведен анализ исходных данных модулей, входящих в государственную интегрированную информационную систему управления общественными финансами «Электронный бюджет», и подлежащих доработке в целях обеспечения соответствия требованиям план-заданий на доработку ППО.
По результатам анализа исходных данных спроектированы решения для обеспечения полноты реализации функциональных и технологических требований план-заданий на доработку ППО и автоматизации бизнес-процессов исполнения функций (части функций).
Перечень выполненных план-заданий приведен в документе «Реестр План-заданий на доработку прикладного программного обеспечения ГИС Минфина России», Договор от 29.08.2024 года № ЕИ_26_0003502_2024 «Выполнение работ по адаптационному сопровождению подсистем, (компонент, модулей) государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет» в части модуля организации предоставления в электронном виде мер государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам – производителям товаров, работ, услуг Министерства финансов Российской Федерации». Количество выполненных модификаций в соответствии с планом модификации подсистем (компонентов, модулей) ГИИС «Электронный бюджет»: 1 штук.
Общее количество модификаций по доведенным Минфином России составляет {num_plan_task} план-заданий. Модификации проведены для подсистем (компонентов, модулей) ГИИС «Электронный бюджет» в том числе:
модуль организации предоставления в электронном виде мер государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам – производителям товаров, работ, услуг.

Проведено тестирование доработанного ППО на тестовом контуре и проведена установка изменений в промышленном контуре информационно-телекоммуникационной инфраструктуры Заказчика в соответствии с установленными в Техническом задании требованиями.

Подготовлены комплекты технорабочей документации на адаптированное (модифицированное) ППО. Разработка комплектов программной документации осуществлялась согласно требованиям приказа Минфина России от 27 апреля 2017 г. № 67н «Об утверждении Положения о порядке разработки и утверждения документации, касающейся государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет», составе и требованиях к ее содержанию». 
Разработанные комплекты документации представлены на магнитных носителях записи.

По итогам выполнения работ доработано ППО, включая исходные коды, а также подготовлен реестр план-заданий и документы «Отчет о выполненной адаптации (модификации) ППО». Сведения о фактической трудоемкости приведены в Приложение 1. Дистрибутивы модифицированного ППО, актуализированные комплекты технорабочей документации, эксплуатационной документации и документации, используемой в процессах проведения испытаний в качестве результатов выполнения работ, представлены на оптических носителях данных (см. Ведомость машинных носителей).

== Выполнение работ по поддержке в актуальном состоянии информационного обеспечения ГИС Минфина (п. 3.6.2 Технического задания Договора)

В соответствии с требованиями, изложенными в п. 3.6.2 «Поддержка в актуальном состоянии информационного обеспечения ГИС Минфина» Технического задания Договора:

обеспечена поддержка в актуальном состоянии форм документов, классификаторов, нормативной базы и реализованных решений;

по требованию Заказчика обеспечено ведение согласованного перечня классификаторов (справочников) посредством оперативного внесения изменений, в сроки, установленные порядком ведения таких классификаторов (справочника), поступающих от Заказчика (либо из иного, согласованного Заказчиком источника) изменений;

обеспечена разработка форматов приема/передачи файлов, электронных документов и/или наборов информации (далее – ТФФ), используемых при межсистемном информационном взаимодействии ППО и при организации информационного взаимодействия с внешними информационными системами.

При разработке ТФФ:

* обеспечен анализ нормативных правовых актов и технорабочей документации, касающихся объектов информационного обмена;
* обеспечен анализ объектов информационного обмена, сведения по которым подлежат приему/передаче в электронной форме;
* обеспечена разработка формализованного описания сведений, передаваемых в структурированном виде;
* разработано текстовое описание передаваемых сведений в виде ТФФ;
* подготовленные ТФФ согласованы с Заказчиком.

== Выполнение требований по разработке отчетной документации, технорабочей и эксплуатационной документации на ППО (разделом 4 Технического задания Договора)

В соответствии с требованиями раздела 4 «Требования к составу и содержанию документов» Технического задания Договора, изготовлены комплекты технической и эксплуатационной документации в составе, определенном Положением о документации, разрабатываемой в рамках создания и развития государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет».

Разработаны и направлены на согласование Заказчику комплекты технорабочей документации, изготовленные в соответствии с требованиями приказа Минфина России от 27 апреля 2017 г. № 67н «Об утверждении Положения о порядке разработки и утверждения документации, касающейся государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет», составе и требованиях к ее содержанию».

Выполнены работы по разработке плана проведения работ по внесению изменений в ППО, отчета о результатах выполнения работ и отчета о выполненной адаптации (модификации) ППО. 

Отчетная документация, исходный код, дистрибутив и комплекты конструкторской документации представлены на магнитном носителе данных.

<<<<
== Перечень приложений

По разделу 5. Технического задания:

include::tables/t_list_application.adoc[]
. Диск с отчетными материалами (на диске должны присутствовать: План проведения работ по внесению изменений в ППО, Реестр План-заданий, Ведомость машинных носителей информации, Отчет о результатах выполнения работ, Отчеты о выполненной адаптации (модификации), папка DOC).
. Дистрибутив программного средства и комплекты конструкторской документации в электронном виде на оптическом носителе данных.




include::tables/t_application_1_report.adoc[]

[.portrait]
<<<<
include::tables/t_podpis.adoc[]

<<<<
include::tables/t_list_change.adoc[]
