:figure-caption!:
:image-size: width=642, height=auto
:image-size1: width=400, height=auto 
:image-size2: width=320, height=auto 
:imagesdir: ../images/
:iconsdir: ../icons/
:image-default-align: center
:doctype: book
:sectnums:
:xrefstyle: full
:section-refsig: разделе
include::master_text.adoc[]
:docinfo: shared

== Введение

=== Общие сведения о Модуле

Модуль организации предоставления в электронном виде мер государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам – производителям товаров, работ, услуг, подсистемы управления расходами государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет» (далее – Модуль) в рамках выполнения работ по развитию (модернизации) государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет» в части расширения функциональных возможностей подсистемы управления расходами, предназначен для формирования и публикации подробной информации о субсидии для информирования потенциальных заявителей об особенностях предоставляемой субсидии. 
И проведения процедуры отбора получателей субсидий (формирование и публикация объявления об отборе, прием и рассмотрение заявок участников отбора на соответствие требованиям, оценка заявок по показателям и критериям оценки, формирование и утверждение протоколов по результатам этапов отбора).

=== Целевые категории пользователей

Модуль предназначен для использования следующими категориями пользователей (участниками модуля):

* участники системы «Электронный бюджет», определенные постановлением Правительства Российской Федерации от 30 июня 2015 г. № 658 «О государственной интегрированной информационной системе управления общественными финансами «Электронный бюджет»;
* участники проектной деятельности в Правительстве Российской Федерации, определенные постановлением Правительства Российской Федерации от 31 октября 2018 г. № 1288 «Об организации проектной деятельности в Правительстве Российской Федерации»;
* лица и организации, определенные разделом VI Положения о системе управления государственными программами Российской Федерации, утвержденного постановлением Правительства Российской Федерации от 26 мая 2021 г. № 786 «О системе управления государственными программами Российской Федерации».

=== Краткое описание возможностей

В модуле реализованы следующие автоматизированные функции, направленные на достижение установленных целей выполнения работ по сопровождению информационных систем Министерства финансов Российской Федерации в 2021 году, в рамках создания модуля является:

*	регистрация и однократная авторизация, и идентификация пользователей, которая проходит с использованием ЕСИА;
*	дополнение поступившей из системы «Электронный бюджет» информации о субсидии (формирование профиля субсидии), отправкой на согласование и утверждение усиленной квалифицированной электронной подписью уполномоченного лица с последующей публикацией на публичной части (с предварительным просмотром информации), как на Портале мер финансовой поддержки, так и на Единый портал государственных и муниципальных услуг;
*	формирование отборов получателей субсидий в соответствии с правилами предоставления субсидий, установленными нормативными правовыми актами и иными документами в установленной сфере деятельности, с возможностью настроек: основных характеристик организуемого отбора, добавления категорий участников, настройки графика проведения отбора, настройки шаблона заявки под каждый отбор получателей субсидии, настройки критериев (показателей) допуска к отбору и экспертной оценки заявок, настройки расчета значений экспертной оценки заявок и распределение средств по годам и КБК. Отправка объявления об отборе на согласование и утверждение усиленной квалифицированной электронной подписью уполномоченного лица с последующей публикацией и отображением информации о ходе проведения отбора получателей субсидии в публичной части (с предварительным просмотром информации);
*	формирование и подача заявки на участие в отборе получателей субсидий, а также возможностью отзыва заявки и ее подписание усиленной квалифицированной электронной;
*	назначение валидаторов на поступившие заявки, а также приглашение и распределение на заявки экспертов (если предусмотрено два этапа проведения отбора), формирование списка членов конкурсной комиссии отбора получателей субсидии и условий утверждения протоколов, формируемых в процессе отбора получателей субсидий, на Портале и настройка ограничений доступа к подписанию протоколов в соответствии с сформированными списками членов конкурсных комиссий;
*	просмотр «Профиля получателя субсидии» предоставляющего главному распорядителю бюджетных средств, организатору отбора, членам конкурсной комиссии и валидатору сводную информацию об участнике отбора, получателе средств, основанную на его "цифровом следе" в государственных информационных системах, иных информационных системах и позволяющего оценить деловую репутацию участника, возможные риски, связанные с исполнением соглашений о предоставлении субсидий;
*	рассмотрение поступивших заявок и принятие решения о допуске/не допуске заявок к экспертной оценке и проведение экспертом оценки (если предусмотрено два этапа проведения отбора), формирования экспертного заключения с подписанием усиленной квалифицированной электронной подписью или простой электронной подписью;
*	формирование и отправка на согласование и подписание усиленной квалифицированной электронной подписью уполномоченного лица протоколов, предусмотренных при проведении отбора получателей субсидий;
*	возможность создания чат-групп организатором отбора и ведение диалогов. Возможность автоматического создания чат-групп по событию, уведомление средствами Портала участников отборов об изменении статуса отбора, о ходе участия в отборе, проактивное уведомление об объявлении новых отборов в зависимости от информации об участнике отбора.

=== Уровень подготовки пользователя

Пользователи модуля должны обладать навыками работы с операционной системой Windows версии 8.1 и выше, а также навыками работы с интернет-обозревателем (например, Яндекс. Браузер, Google Chrome, КриптоПро-Fox). 
Перед началом работы с модулем пользователи, не обладающие такими навыками, должны пройти соответствующие курсы повышения компьютерной грамотности.

=== Перечень эксплуатационной документации, с которой необходимо ознакомиться пользователю

Для работы с модулем пользователю необходимо ознакомиться с данным руководством.