include::master_text.adoc[]
:table-caption!: 
:figure-caption!:
:doctype: book
:imagesdir: ../images/
:iconsdir: ../icons/
:table-caption!: 
:docinfo: shared

// Для нескольких ролей Просмотр реестра заявителей
// используется в РП 4, РП 22 

== Перечень терминов и сокращений

Перечень сокращений, терминов и определений представлен в <<id_table_l_term_1, Таблице {counter:table-number}>>.

[[id_table_l_term_1]]
.Таблица {counter:table-number}. Перечень терминов и сокращений
ifndef::cz[]
include::../tables/t_l_term_1.adoc[]
endif::[]
ifdef::cz[]
include::../tables/t_l_term_1_cz.adoc[]
endif::[]

<<<<
:table-caption!: 

== Введение

{nast_doc} ролей 
ifndef::cz[«{role_grbs}»,]
«{role_oo}», «{role_kk}» и «{role_val}», {used} 
ifndef::cz[]
сводной информации о заявителях в сервисе Профиль получателя, а именно информации о Заявителях, о результатах прохождения проверок различными государственными информационными системами, о статистике по соглашениям, о статистике по выполнению контрактов. 
endif::[]
ifdef::cz[]
просмотру реестровых записей, содержащих сведения о пользователях получивших аккредитацию, в соответствии с требованиями постановления Правительства Российской Федерации от 19 мая 2021 г. № 757 «Об утверждении Правил формирования и ведения реестра участников конкурса на заключение соглашения об оказании государственных (муниципальных) услуг в социальной сфере, получивших аккредитацию в соответствии с Федеральным законом «О государственном (муниципальном) социальном заказе на оказание государственных (муниципальных) услуг в социальной сфере». 
endif::[]

{func} <<id_table_4, Таблице {counter:table-number}>>.

[[id_table_4]]
.Таблица {counter:table-number}. Функции и полномочия
ifndef::cz[]
include::../tables/t_intro_4.adoc[]
endif::[]
ifdef::cz[]
include::../tables/t_intro_4_cz.adoc[]
endif::[]