:docinfo: shared
:table-caption!: 
//:cz:
//Для заявителя

// Главы Перечень терминов и сокращений и Введение, для ролей Заявитель и Эксперт
// Содержится в РП 3, РП 8, РП 13, РП 14, РП 15, РП 16, РП 18, РП 20, title_test.adoc

== Перечень терминов и сокращений

Перечень сокращений, терминов и определений представлен в <<id_table_l_term_1, Таблице {counter:table-number}>>.

[[id_table_l_term_1]]
.Таблица {counter:table-number}. Перечень терминов и сокращений
ifndef::cz[]
include::../tables/t_l_term_2.adoc[]
endif::[]
ifdef::cz[]
include::../tables/t_l_term_2_cz.adoc[]
endif::[]

<<<<
:table-caption!: 

== Введение

ifdef::manual3[]
Руководство пользователя включает в себя детальное описание и пошаговые инструкции по процессу создания, заполнения и подачи заявки для участия в отборе на предоставление субсидии на Портале государственной финансовой поддержки (далее – Портал).
endif::[]

ifdef::manual8[]
{nast_doc} роли «{role_exp}», {used} проведению процедуры оценки заявок поданных для участия в отборе получателей субсидий на Портале предоставления мер финансовой государственной поддержки (далее – Портал). 
endif::[]

ifdef::manual13[]
Руководство пользователя содержит описание и подробные инструкции по ведению диалогов в чат-группах на Портале предоставления мер финансовой государственной поддержки (далее – Портал).
endif::[]

ifdef::manual14[]
Руководство пользователя содержит описание и подробные инструкции по предоставлению данных для формирования соглашения и подписанию соглашения после успешного прохождения отбора и просмотр содержимого всех отчетов доступных по соглашению на Портале предоставления мер финансовой государственной поддержки (далее – Портал). 
endif::[]

ifdef::manual15[]
Руководство пользователя о процессе получения аккредитации согласно требованиям, установленным постановлением Правительства Российской Федерации от 19 мая 2021 года № 757 «Об утверждении Правил формирования и ведения реестра участников конкурса на заключение соглашения об оказании государственных (муниципальных) услуг в социальной сфере, получивших аккредитацию в соответствии с Федеральным законом «О государственном (муниципальном) социальном заказе на оказание государственных (муниципальных) услуг в социальной сфере». 
В руководстве также предоставляются инструкции по внесению изменений, аннулированию и продлению аккредитации на Портале предоставления мер финансовой государственной поддержки (далее – Портал). 
endif::[]

ifdef::manual16[]
Руководство пользователя содержит описание и подробные инструкции по установке плагина КриптоПро, плагина Госуслуг и установке сертификата электронной подписи для участия в отборе на Портале предоставления мер финансовой государственной поддержки (далее – Портал). 
Предусловием является, что ранее пользователь получил электронную подпись ЮЛ/ИП/ФЛ в удостоверяющем центре ФНС России, Банка России, Федерального казначейства или организации, осуществляющей деятельность в соответствии с Федеральным законом от 10 июля 2002 года N 86-ФЗ. 
endif::[]

ifdef::manual18[]
Руководство пользователя содержит описание и подробные инструкции по созданию, заполнению заявки и ее подачи для участия в отборе исполнителей услуг на Портале предоставления мер финансовой государственной поддержки (далее – Портал). 
endif::[]

ifdef::manual20[]
{nast_doc} роли «{role_exp}», {used} проведению процедуры оценки заявок поданных для участия в отборе исполнителей услуг по социальному заказу путем проведения конкурса на Портале предоставления мер финансовой государственной поддержки (далее – Портал).
endif::[]