include::master_text.adoc[]
:table-caption!: 
:figure-caption!:
:doctype: book
:imagesdir: ../images/
:iconsdir: ../icons/
:table-caption!:
:docinfo: shared

// Главы Перечень терминов и сокращений и Введение, где отражена таблица полномочий Организатора отбора
//Используется для РП2, РП7, РП9, РП10, РП 11, РП12 (субсидийные) и РП17, РП21, РП23 (соц заказ) в последующем можно оптимизировать (объединить условиями с интро-1)

== Перечень терминов и сокращений

Перечень сокращений, терминов и определений представлен в <<id_table_l_term_1, Таблице {counter:table-number}>>.

[[id_table_l_term_1]]
.Таблица {counter:table-number}. Перечень терминов и сокращений
ifndef::cz[]
include::../tables/t_l_term_1.adoc[]
endif::[]
ifdef::cz[]
include::../tables/t_l_term_1_cz.adoc[]
endif::[]

<<<<
:table-caption!: 

== Введение

// Для РП 2 
ifdef::manual2[]
{nast_doc} роли «{role_oo}», {used} настройке отбора получателей субсидии, согласованию, утверждению и публикации объявления об отборе на Портале.
endif::[]

// Для РП 7
ifdef::manual7[]
{nast_doc} роли «{role_oo}», {used} формированию списка экспертов, приглашению экспертов из сформированного списка на отбор получателей субсидий / отборов исполнителей услуг по социальному заказу и распределению экспертов на заявки для последующего проведения ими экспертной оценки.

{two_stage}.
endif::[]

// Для РП 9
ifdef::manual9[]
{nast_doc} роли «{role_oo}», {used} определению победителей и распределению средств субсидии по победителям отбора.
endif::[]

// Для РП 10
ifdef::manual10[]
{nast_doc} роли «{role_oo}», {used} формированию и утверждению протоколов процедур отбора получателей субсидий без проведения экспертизы заявок (одноэтапный отбор):

* протокол вскрытия заявок;
* протокол подведения итогов отбора.
endif::[]

// Для РП 11
ifdef::manual11[]
{nast_doc} роли «{role_oo}», {used} формированию и утверждению протоколов процедур отбора получателей субсидий с проведением экспертизы заявок (двухэтапный отбор):

* протокол вскрытия заявок;
* протокол рассмотрения заявок;
* протокол подведения итогов отбора.
endif::[]

// Для РП 12
ifdef::manual12[]
{nast_doc} роли «{role_oo}», {used} настройке и формированию Диалогов. 
endif::[]

// Для РП 17
ifdef::manual17[]
{nast_doc} роли «{role_oo}», {used} настройке отбора исполнителей услуг, согласованию, утверждению и публикации объявления об отборе на Портале.
endif::[]

// Для РП 21
ifdef::manual21[]
{nast_doc} роли «{role_oo}», {used} определению победителей и распределению объемов услуг по победителям отбора исполнителей услуг по социальному заказу после завершения конкурса на Портале. 
endif::[]

// Для РП 23
ifdef::manual23[]
{nast_doc} роли «{role_oo}», {used} формированию и утверждению протоколов процедур отбора исполнителей услуг:

* протокол вскрытия заявок;
* протокол рассмотрения заявок;
* протокол подведения итогов отбора.
endif::[]

{func} <<id_table_2, Таблице {counter:table-number}>>.

//Таблица терминов и часть Введение с таблицей полномочий для role2 \ role2_cz
[[id_table_2]]
.Таблица {counter:table-number}. Функции и полномочия
ifndef::cz[]
include::../tables/t_intro_2.adoc[]
endif::[]
ifdef::cz[]
include::../tables/t_intro_2_cz.adoc[]
endif::[]