include::contract.adoc[]

:sectnums: 
[%breakable]
== Характеристика объекта автоматизации

Минфин России реализацию своих функций осуществляет, в том числе с использованием ГИС Минфина России, эксплуатируемых в специально организованной информационно-технической инфраструктуре Государственного заказчика, представляющей собой совокупность систем инженерного обеспечения, каналов и линий связи, локально-вычислительной сети (в составе контуров: выделенной локальной вычислительной сети, закрытой корпоративной вычислительной сети и Интернет корпоративной вычислительной сети), общесистемного программного обеспечения, включая СУБД, СХД и серверного оборудования, рабочих станций пользователей.

Пользователями ППО являются сотрудники Минфина России, государственных органов власти, органов местного самоуправления, органов управления государственными внебюджетными фондами, государственных и муниципальных учреждений и юридических лиц, индивидуальные предприниматели, крестьянские (фермерские) хозяйства, получающие средства из бюджетов бюджетной системы Российской Федерации в соответствии с бюджетным законодательством Российской Федерации, иных юридических и физические лица при реализации правоотношений с участниками бюджетного процесса, а также юридических лиц, указанных в части 2 статьи 1Федерального закона «О закупках товаров, работ, услуг отдельными видами юридических лиц», использующие систему «Электронный бюджет» для реализации бюджетных полномочий, ведения финансово-хозяйственной деятельности, обмена документами в рамках заключения и исполнения гражданско-правовых договоров, казначейского сопровождения, реализации иных правоотношений с участниками бюджетного процесса и (или) для формирования и предоставления информации, в том числе для размещения на едином портале бюджетной системы Российской Федерации, в единой информационной системе в сфере закупок, и получения информации в целях реализации функций и полномочий.

Кроме того, пользователями ГИС Минфина России являются участники проектной деятельности в Правительстве Российской Федерации – уполномоченные работники федеральных органов исполнительной власти, органов исполнительной власти субъектов Российской Федерации, федерального проектного офиса, ведомственных проектных офисов, региональных проектных офисов, члены проектных комитетов, иные лица, являющиеся экспертами (контролерами, членами рабочих групп и т.п.), в рамках осуществления проектной деятельности, представители органов местного самоуправления, а также уполномоченных работников иных юридических лиц – участников проектов.


