include::contract.adoc[]

:sectnums: 

[%breakable]
== Требования к документированию
[%breakable]
=== Общие требования к отчетным материалам

Сдача-приемка выполненных работ осуществляется в соответствии с условиями Договора и Технического задания и оформляется в виде Акта сдачи-приемки выполненных работ с приложением соответствующих отчетных документов, согласно требованиям, раздела 5 Технического задания. Все отчетные материалы передаются с сопроводительными документами Исполнителя в 2 (двух) экземплярах на бумажном носителе и на 1 (одном) CD /DVD-диске.
Отчет о выполненных работах за отчетный период должен содержать полную информацию о выполненных работах, которые были осуществлены Исполнителем. 
Текстовые документы, передаваемые на машинных носителях, должны быть представлены в форматах .DOC (.DOCX), .XLS (.XLSX), .PPT (.PPTX), PDF.
[%breakable]
=== Требования к разработке технорабочей документации

В рамках работ Исполнитель должен обеспечить подготовку отчетной документации, техно-рабочей и эксплуатационной документации на ППО в соответствии с требованиями Технического задания и приказа Минфина России от 27 апреля 2017 г. № 67н.




