include::contract.adoc[]

:sectnums: 

=== Требования к видам обеспечения

==== Требования к надежности

Модуль должен обеспечивать хранение информации обо всех действиях пользователей (внесение, изменение, удаление и т.п.) в отношении объектов данных. При этом должны быть зафиксированы как минимум следующие данные: пользователь, дата выполнения операции и ее тип, идентификатор изменяемого объекта и параметры изменения для данного объекта.

==== Требования к эргономике и технической эстетике

Экранные формы должны проектироваться с учетом требований унификации:

* все экранные формы пользовательского интерфейса в рамках каждой из функциональных систем, должны быть выполнены в едином графическом дизайне, с одинаковым расположением основных элементов управления и навигации;
* для обозначения одних и тех же операций в рамках каждой из функциональных систем, создаваемых в объеме работ по государственному контракту, должны использоваться одинаковые графические значки, кнопки и другие управляющие (навигационные) элементы; должен быть унифицированы термины, используемые для описания идентичных понятий, операций и действий пользователя;
* реакция системы на действия пользователя (наведение указателя «мыши», переключение фокуса, нажатие кнопки) должна быть типовой в рамках каждой из функциональных систем, создаваемых в объеме работ по государственному контракту, для каждого действия над одними и теми же графическими элементами, независимо от их расположения на экране;
* все подсистемы, компоненты, модули в рамках функциональной системы должны быть реализованы в единой технологической архитектуре, использовать единые стандарты извлечения, обработки и представления информации, обмениваться информацией между комплексами задач по единым стандартам и форматам, обеспечивать единую логику при работе пользователя с однотипными объектами.

==== Обеспечение требований информационной безопасности

// tag::security_requirements[]
Архитектура безопасности Модуля мер поддержки должна быть основана на механизмах обеспечения информационной безопасности:

* идентификации и аутентификации (в части блокирования идентификаторов);
* управления доступом;
* регистрации событий безопасности.

Механизмы безопасности Модуля мер поддержки должны быть реализованы посредством обеспечения мер защиты, реализующих функции безопасности, применяемые в соответствии с требованиями документа «Требования о защите информации, не составляющей государственную тайну, содержащейся в государственных информационных системах» (введен в действие приказом ФСТЭК России № 17 от 11 февраля 2013 г.).
ПО Модуля мер поддержки должно реализовывать следующие меры защиты:

* управление идентификаторами;
* управление (блокирование) учетными записями пользователей;
* реализация необходимых методов (ролевой модели) и правил разграничения доступа;
* разделение полномочий (ролей) пользователей, администраторов и лиц, обеспечивающих функционирование информационной системы;
* блокирование сеанса доступа в информационную систему после установленного времени бездействия (неактивности) пользователя или по его запросу;
* разрешение (запрет) действий пользователей, разрешенных до идентификации и аутентификации; 
* определение событий безопасности, подлежащих регистрации, и сроков их хранения;
* определение состава и содержания информации о событиях безопасности, подлежащих регистрации;
* сбор, запись и хранение информации о событиях безопасности в течение установленного времени хранения;
* генерирование временных меток и (или) синхронизация системного времени в информационной системе;
* защита информации о событиях безопасности.
// end::security_requirements[]

==== Требования к сохранности информации при авариях

Кроме этого, должны соблюдаться следующие требования:

* сохранность информации должна обеспечиваться при всех аварийных ситуациях;
* в случае повреждения журналов транзакций СУБД должно быть обеспечено восстановление состояния ИС Минфина России на момент создания последней резервной копии данных, но не позднее, чем за сутки до момента сбоя;
* в Модуле должны быть предусмотрены механизмы, обеспечивающие выполнение регламента по обеспечению сохранности информации в случае выхода из строя оборудования, а также политики защиты данных и требований к средствам и способам хранения резервных копий.

==== Требования к патентной чистоте

Дополнительно, для работ, выполняемых в соответствии с требованиями настоящего Частного технического задания, при разработке результатов, способных к правовой охране (в соответствии со статьей 1225 Гражданского кодекса Российской Федерации), необходимо обеспечить проведение патентных исследований по согласованию с Государственным заказчиком.
При выполнении работ должны быть использованы только такие объекты интеллектуальной собственности, права на которые приобретены (получены) и используются без нарушений прав на интеллектуальную собственность третьих лиц. Это требование должно обеспечивать соблюдение авторских, смежных, патентных и иных прав.

Все стороннее ПО, используемое Исполнителем для выполнения работ, должно быть свободно распространяемым, но не налагающим обязательства на Государственного заказчика предоставления внешним организациям переданного Государственному заказчику исходного кода, и (или) разработанным в Российской Федерации (государстве-члене Евразийского экономического союза, за исключением Российской Федерации) и содержаться в Реестре российского ПО (Реестре евразийского ПО), согласно постановлению Правительства Российской Федерации от 16 ноября 2015 г. № 1236 «Об установлении запрета на допуск программного обеспечения, происходящего из иностранных государств, для целей осуществления закупок для обеспечения государственных и муниципальных нужд». Данное стороннее ПО не должно иметь ограничений на использование его на всей территории Российской Федерации с возможностью предоставления права его использования Исполнителем Государственному заказчику и дальнейшего предоставления Государственным заказчиком права его использования третьим лицам. Стоимость лицензионного вознаграждения за предоставление Государственному заказчику права использования Стороннего ПО подлежит включению в стоимость Государственного контракта. Право использования стороннего ПО должно быть предоставлено заказчику на весь срок действия исключительного права на данное стороннее ПО. Предоставление права использования стороннего ПО должно быть выполнено силами Исполнителя и за его счет.
Готовые, настраиваемые компоненты должны быть лицензированы согласно лицензионному соглашению фирмы-производителя.

[%breakable]
==== Требования к стандартизации и унификации

Кроме этого, должны соблюдаться следующие требования:

* системная архитектура в рамках каждой из подсистем (компонентов, модулей), создаваемых в объеме работ, должна быть построена на основе унифицированных технических решений;
* ППО в рамках каждой из создаваемых подсистем (компонентов, модулей), должно быть построено с использованием стандартных и унифицированных методов разработки программных систем;
* в составе Модуля, по возможности, должны применяться типовые (унифицированные) классификаторы и справочники, действие которых на территории Российской Федерации определено соответствующими нормативными актами и стандартами. В Модуле должна быть предусмотрена возможность наращивания классификаторов и справочников;
* работы по развитию Модуля должны вестись с учетом необходимости публикации данных, содержащихся в Системе «Электронный бюджет», в формате открытых данных;
* документирование должно соответствовать действующей редакции «Положения о порядке разработки и утверждения документации, касающейся государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет», составе и требованиях к ее содержанию» (или иному документу, который может быть введен в действие взамен указанного).

