include::contract.adoc[]

:sectnums: 
[%breakable]
== Состав и содержание работ
[%breakable]
=== Перечень этапов работ и сроки их выполнения

:num_t: {counter:table-number}

Работы по адаптации (модификации) ППО  должны осуществляться в соответствии с требованиями xref:#section-6[пункта 6 «Порядок разработки»] настоящего документа, согласно составу и срокам, приведенным в <<id_t_{num_t}, Таблице {num_t}>>.
[%breakable]
[#id_t_{num_t}]
.Таблица {num_t}. Этапы работ и сроки их выполнения
include::../tables/t_deadlines_chapter_5.adoc[]

В случае расторжения Государственного контракта Исполнитель обязан передать по акту все имеющиеся у него материалы, относящиеся к результатам выполнения работ по Государственному контракту, оформленные в соответствии с настоящим Частным техническим заданием, уполномоченному Государственным заказчиком представителю.
Исполнитель не вправе распространять информацию о выполняемых работах по Государственному контракту и полученных результатах, а также не должен использовать в собственных целях и в целях третьих лиц информацию, которая связана с выполнением работ по Государственному контракту. Все результаты работ, выполненных в рамках Государственного контракта, являются собственностью Минфина России.
Правообладателем исключительных прав на вновь созданное (модифицированное) по Государственному контракту ППО системы «Электронный бюджет» является Минфин России.










