:sectnums: 

[%breakable]
== Общие сведения

[%breakable]
=== Полное наименование работы 

// tag::intro[]
Выполнение работ по адаптационному сопровождению подсистем (компонентов, модулей) государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет» в части модуля организации предоставления в электронном виде мер государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам - производителям товаров, работ, услуг (далее – Модуль) Министерства финансов Российской Федерации в {year} году (далее – работы) в соответствии с требованиями, установленными в Техническом задании, являющемся Приложением №1 к Договору {сontract_number} (далее – ТЗ). 
// end::intro[]

[%breakable]
=== Перечень документов-оснований для выполнения работ

// tag::legal_basis[]
Работы по адаптации (модификации) прикладного программного обеспечения (ППО) Модуля выполняются на основании план-заданий на доработку, формируемых Государственным заказчиком. При выполнении работ Исполнитель должен руководствоваться нормативными правовыми актами и регламентирующими документами, указанными в ТЗ, в том числе:

* план АЦ по клиентоцентричности для сертификации в лаборатории пользовательского тестирования;
* план по реализации «карты болей» (5.3) Дорожная карта «Субсидии». 

// end::legal_basis[]
[%breakable]
=== Сроки выполнения работ

Срок выполнения работ по {po_planu}: c {data_applic_1_start} по {data_applic_1_end}. 
