include::contract.adoc[]

:sectnums: 

[%breakable]
[[section-6]]
== Порядок разработки
[%breakable]
=== Порядок организации разработки

Работы по адаптации (модификации) ППО по основаниям, предусмотренным разделом 2.4 Технического задания, выполняются на основании формируемых Государственным заказчиком План-заданий на доработку (далее – план-задание), направляемых Заказчиком в адрес Исполнителя. В план-задании должен быть указан конкретный срок выполнения работ по адаптации (модификации) ППО.
Предлагаемые решения должны обеспечивать полноту реализации функциональных и технологических требований к автоматизации бизнес-процессов исполнения функций (части функций). В процессе выполнения работ по адаптации (модификации) ППО Исполнитель не должен изменять используемую аппаратно-программную платформу без согласования с Государственным заказчиком.
По итогам выполнения работ Исполнителем предоставляются доработанное ППО, включая исходные коды, и Отчет о выполненной адаптации (модификации) ППО. Исполнитель должен провести тестирование доработанного ППО на тестовом контуре и при успешном завершении выполнить установку изменения в промышленном контуре ИТ-инфраструктуры Государственного заказчика в соответствии с установленными Техническим заданием требованиями. 
[%breakable]
=== Перечень документов, предъявляемых по окончании соответствующих этапов работ

В целях поддержания техно-рабочей документации ППО в актуальном состоянии Исполнителем по завершении выполнения работ:

. Актуализируются данные проектного репозитория централизованного репозитория исходного кода ППО в части исходного кода, дистрибутивов.
. Подготавливаются комплекты техно-рабочей документации на адаптированное (модифицированное) ППО. 

Исполнителем должны подготавливаться комплекты документации для проведения комплексных испытаний (проекты протоколов испытаний, актов ввода в эксплуатацию, отчетов о проведении опытной эксплуатации), если Государственным заказчиком принято решение о целесообразности их проведения.
Государственному заказчику и Заказчику направляется информационное письмо о завершении комплекса работ по адаптации (модификации) ППО, функционального и нагрузочного тестирования, в случае проведения.
При разработке комплектов программной документации (согласно требованиям приказа Минфина России от 27 апреля 2017 г. № 67н) Исполнитель должен руководствоваться документами, представленными Заказчиком, методическими рекомендациями, национальными стандартами и руководящими документами по стандартизации.


:num_t: {counter:table-number}
Перечень документов предъявляемых по окончании соответствующих этапов работ в соответствии с «Положением о порядке разработки и утверждения документации, касающейся государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет», составе и требованиях к ее содержанию» [2], указан в <<id_t_{num_t}, Таблице {num_t}>>.
[%unbreakable]
[#id_t_{num_t}]
.Таблица {num_t}. Перечень документов, этапы и сроки их создания
include::../tables/t_list_doc.adoc[]







