include::contract.adoc[]

:sectnums: 
[%breakable]
== Требования к выполнению работ
[%breakable]
=== Требования к адаптации (модификации) ППО

Работы по адаптации (модификации) ППО по основаниям, предусмотренным разделом 2.4 Технического задания, выполняются на основании формируемых Государственным заказчиком План-заданий на доработку (далее – план-задание), направляемых Заказчиком в адрес Исполнителя. 
Исполнитель в рамках выполнения работ обеспечивает в соответствии с поступающими обращениями Заказчика:

. Внесение изменений в ППО в части его прикладных функций в связи с изменениями нормативных правовых актов, в целях совершенствования исполнения существующих автоматизируемых функций и процессов и / или оптимизации быстродействия ППО, включая доработку экранных (в том числе вёрстку веб-страниц) и печатных форм, алгоритмов обработки информации, сервисов информационного взаимодействия и форматов обмена данными, иных объектов ППО.
. Поддержка в актуальном состоянии информационного обеспечения ГИС
Минфина России, включая формирование средствами разработки и отладки ППО выборок из баз данных (непредусмотренных штатными средствами ППО) и загрузок в них данных из внешних массивов информации, включая при необходимости выполнение операций по приведению информационных массивов к виду, пригодному для автоматизированной обработки.
. Внесение изменений в техно-рабочую документацию, пользовательские инструкции и иные документы в соответствии с внесенными изменениями в ППО.

[%breakable]
=== Требования к структуре и функционированию

Модуль должен сохранять структуру и функционировать в соответствии с установленными требованиями к информационной системе «Электронный бюджет». Модуль должен быть легко интегрирован с другими подсистемами «Электронного бюджета». Модуль должен обеспечивать полный цикл работы с заявками на получение мер государственной финансовой поддержки: от подачи заявки до принятия решения о ее предоставлении или отклонении.

:num_t: {counter:table-number}
Модуль включает в себя следующие функциональные уровни и компоненты, приведенные в <<id_t_{num_t}, Таблице {num_t}>>.
[%unbreakable]
[#id_t_{num_t}]
.Таблица {num_t}. Функциональные уровни и компоненты 
include::../tables/tables.adoc[tag=table_func_level]




