include::contract.adoc[]

// первая часть документа до ФТ
//****************************** */
// tag::start_section[]

//Служеб. настрока титульника. Менять год здесь
// include::title_page.adoc[]
include::../tables/titul_report.adoc[]
//Автоматическая таблица содержания, отражает организацию разделов
<<<<
toc::[]
<<<<
// Перечень терминов и сокращений


// tag::report_intro[]
:!sectnums: 
[%breakable]
== Введение 

Исполнителем работ – Обществом с ограниченной ответственностью «МИРТЕХ» выполнен полный объем работ по {stage} этапу, предусмотренных требованиями Раздела 5 «Календарный план выполнения работ» Приложения 1 «Техническое задание» (далее Техническое задание) к Договору {сontract_number} «Выполнение работ по адаптационному сопровождению подсистем, (компонент, модулей) государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет» в части модуля организации предоставления в электронном виде мер государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам - производителям товаров, работ, услуг Министерства финансов Российской Федерации» (далее – Договор). 
// end::report_intro[]
Работы, предусмотренные требованиями Договора, проводились по следующему направлению:

* в соответствии с требованиями, изложенными в пункте 3.6.1 «Адаптация (модификация) ППО» Технического задания к Договору выполнены работы по адаптации (модификации) прикладного программного обеспечения (далее ППО).

<<<<
:sectnums: 
== Выполнение работ по адаптации (модификации) ППО (п. 3.6.1. Технического задания)

В соответствии с требованиями, изложенными в пункте 3.6.1 «Адаптация (модификация) ППО» Технического задания к Договору выполнены работы по адаптации (модификации) ППО. Адаптация (модификация) ППО осуществлялась согласно плану проведения работ по внесению изменений в ППО, разработанного в соответствии с подразделом 3.2 «Требования к управлению изменениями» Технического задания к Договору.

В целях обеспечения соответствия ППО требованиям {plana} на доработку ППО осуществлены доработки, представленные в приложении (<<#application_1, Приложение 1>>) настоящего отчета.

Произведен анализ исходных данных модулей, входящих в государственную интегрированную информационную систему управления общественными финансами «Электронный бюджет», и подлежащих доработке в целях обеспечения соответствия требованиям {plana} на доработку ППО.
По результатам анализа исходных данных спроектированы решения для обеспечения полноты реализации функциональных и технологических требований {plana} на доработку ППО и автоматизации бизнес-процессов исполнения функций (части функций).

Проведено тестирование доработанного ППО на тестовом контуре и проведена установка изменений в промышленном контуре информационно-телекоммуникационной инфраструктуры Заказчика в соответствии с установленными в Техническом задании к Договору требованиями.
Подготовлены комплекты технорабочей документации на адаптированное (модифицированное) ППО. Разработка комплектов программной документации осуществлялась согласно требованиям приказа Минфина России от 27 апреля 2017 г. № 67н «Об утверждении Положения о порядке разработки и утверждения документации, касающейся государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет», составе и требованиях к ее содержанию».

Разработанные комплекты документации представлены на магнитных носителях записи.
По итогам выполнения работ доработано ППО, включая исходные коды, а также подготовлен документ «Отчет о выполненной адаптации (модификации) ППО» по форме, установленной регламентом «Регламент оказания услуг по сопровождению государственных информационных систем, оператором которых является Министерство финансов Российской Федерации». 
Сводная информация о фактической трудоемкости работ по адаптации (модификации) ППО представлена в приложении (<<#application_2, Приложение 2>>) настоящего отчета и в качестве результатов работ приведена на магнитном носителе записи.
Актуализированы данные проектного репозитория централизованного репозитория исходного кода информационных систем Минфина России в части исходного кода, дистрибутива, комплектов конструкторской документации на адаптированное (модифицированное) ППО.
// end::start_section[]


// tag::end_section[]
// Подписи
<<<<
include::../tables/t_podpis.adoc[]

// Лист изменений
// <<<<
// include::../tables/t_list_change.adoc[]
// end::end_section[]

//****************************** */