include::common/__period.adoc[]
:docinfo: shared

== Выполнение требований к составу и функционированию СТП (п. 3.1. Технического задания Договора)

В соответствии с требованиями п. 3.1. «Требования к составу и функционированию СТП» Технического задания Договора для ГИС Минфина России:

обеспечено функционирование и оптимизация параметров работы взаимодействующих СТП, для которых выделен телефонный номер (группы телефонных номеров) и адрес (адреса) электронной почты, используемые для приема и исполнения обращений пользователей по вопросам функционирования ППО Модуля мер поддержки;

обеспечены консультационная поддержка в необходимом и достаточном для удовлетворения потребностей пользователей объеме и методические материалы, инструкции, другие документы по вопросам эксплуатации ППО Модуля мер поддержки;

обеспечены регистрация, учет, ведение аудиозаписей и документирование обращений пользователей ППО Модуля мер поддержки с использованием ПСУП и иных программно-технических средств, обеспечивающих возможность формирования по запросу Заказчика отчетных материалов с информацией по каждому обращению;

обеспечены настройка и бесперебойное круглосуточное функционирование ПСУП;

организована многоуровневая структура служб технической поддержки Модуля мер поддержки в следующем составе:

. Первая линия поддержки – персонал, осуществляющий информационно-справочную поддержку пользователей и в обязанности которого входит регистрация поступающих запросов пользователей, их решение с использованием Базы знаний, эскалация запросов на вторую линию (при невозможности решить запрос с использованием Базы знаний), закрытие запросов и контроль качества их исполнения;

. Вторая линия поддержки – персонал, осуществляющий информационно-справочную поддержку пользователей и в обязанности которого входит решение запросов пользователей, которые не были разрешены первой линией поддержки, их анализ, систематизация, выработка решений и включение в Базу знаний, эскалация запросов на третью линию поддержки (при невозможности решить запрос);

. Третья линия поддержки – персонал, занимающийся решением выявленных проблем с данными и ППО, которые не были разрешены второй линией поддержки, их анализ, систематизация, выработка решений и включение в Базу знаний.
