include::common/__period.adoc[]

== Выполнение требований к уровню качества обслуживания (SLA) (п. 3.2. Технического задания Договора)

В соответствии с требованиями, изложенными в п.3.2. «Требования к уровню качества обслуживания (SLA)» Технического задания Договора для Модуля мер поддержки:

обеспечена регистрация и классификация приоритетов инцидентов, определенных в п.3.2. «Требования к уровню качества обслуживания (SLA)» Технического задания Договора;

обеспечено соблюдение параметров качества оказания услуг с учетом ключевых показателей эффективности, определенных в регламенте выполнения работ по сопровождению государственных информационных систем, оператором которых является министерство финансов Российской Федерации;

параметры качества оказания услуг с учетом ключевых показателей эффективности, определенны в <<append_2, *Приложении 2*>> к настоящему документу. 

За период с 01.01.2024 по 26.03.2024 количественные характеристики консультационной поддержки пользователей Модуля мер поддержки, следующие: 

Общее количество обращений в службы технической поддержки пользователей в рамках основного этапа № 1 составило 7521 в том числе:

* с типом «Инцидент» – 2175:
** приоритет «Критичный» – 6;
** приоритет «Высокий» – 108; 
** приоритет «Средний» – 1039;
** приоритет «Низкий» – 1022; 
* с типом «Заявка на консультацию» – 5346: 
** приоритет «Высокий» – 55; 
** приоритет «Средний» – 3926; 
** приоритет «Низкий» – 1365. 

Всего обработано – 7459 обращений: 

* с типом «Инцидент» – 2130; 
* с типом «Заявка на консультацию» – 5329. 

Всего в работе 62 обращение: 

* с типом «Инцидент» – 45; 
* с типом «Заявка на консультацию» – 17. 

За период с 01.01.2024 по 26.03.2024 среднее время отработки обращений составляет: 

* с типом «Инцидент» – 21:05:10; 

* с типом «Заявка на консультацию» – 9:03:01;

* количество консультаций во взаимосвязи с количеством работающих пользователей, % -  7,83;

* доля обращений пользователей, решенных с превышением лимита, определенного соглашением об уровне оказания услуг (SLA), %:
* с типом консультации – 1,05;
* с типом инциденты – 7,63.
* среднее время решения для инцидентов, чч:мин:сек – 21:05:10;
* доля обращений пользователей, решенных непосредственно специалистами первой линии технической поддержки при первом обращении пользователя, % – 70;
* среднее время выполнения автоматизированной процедуры (80-й процентиль), сек. – 0,84;
* количество инцидентов во взаимосвязи с количеством работающих пользователей, ед. –  0,05.

Подготовлена и предоставлена Заказчику и Государственному заказчику оперативная отчетность по работе СТП, статистические и аналитические обзоры по обращениям пользователей, содержащие рекомендации по совершенствованию функциональных и эксплуатационных характеристик ППО Модуля.


