include::common/__period.adoc[]

== Выполнение требований к работе по консультационной и технической поддержке пользователей (п. 3.6. Технического задания Договора)

В соответствии с требованиями, изложенными в п.3.6. «Требования к работе по консультационной и технической поддержке пользователей» Технического задания Договора для Модуля мер поддержки:

обеспечены консультационная и техническая поддержка пользователей, которая включает в себя работы по регистрации, обработке и решению запросов пользователей, связанных с получением информации и функциями, реализованными в ППО, а также работоспособностью и управлением функционированием ППО;

сервисное сопровождение и поддержка пользователей ППО Модуля мер поддержки оказывались в соответствии с параметрами и критериями, приведенными в п.3.2. «Требования к уровню качества обслуживания (SLA)» Технического задания Договора и на основании Регламента выполнения работ по сопровождению государственных информационных систем, оператором которых является министерство финансов Российской Федерации.

