include::common/__period.adoc[]


// [notitle]
== Введение

// [.append-style]
// Введение

Исполнителем работ – Обществом с ограниченной ответственностью {company} выполнен полный объем работ по {step} этапу, предусмотренных требованиями раздела 5 «Календарный план выполнения работ» Приложения № 1 «Техническое задание» (далее Техническое задание) к Договору  № {dogovor} (далее Договор), по сопровождению подсистемы управления расходами в части модуля организации предоставления в электронном виде мер государственной финансовой поддержки юридическим лицам, индивидуальным предпринимателям, а также физическим лицам - производителям товаров, работ, услуг (далее – Модуль мер поддержки), входящей в состав государственной интегрированной информационной системы управления общественными финансами «Электронный бюджет» и оператором которой является Министерство финансов Российской Федерации. Работы, предусмотренные требованиями Договора, проводились по следующим направлениям:

в соответствии с требованиями, изложенными в п.3.1. «Требования к составу и функционированию СТП» Технического задания Договора, обеспечено функционирование и оптимизация параметров работы взаимодействующих служб технической поддержки пользователей Модуля мер поддержки, у которых выделен телефонный номер (группы телефонных номеров) и адрес (адресы) электронной почты, используемые для приема и исполнения обращений пользователей по вопросам функционирования ППО;

в соответствии с требованиями, изложенными в п.3.2. «Требования к уровню качества обслуживания (SLA)» Технического задания Договора, обеспечена классификация приоритетов и регистрация инцидентов с учетом параметров качества оказания услуг, определенных в соответствующем пункте Технического задания Договора;

в соответствии с требованиями, изложенными в п.3.3. «Требования к управлению инцидентами» Технического задания Договора, обеспечена регистрация, классификация, анализ и разрешение инцидентов в соответствии с параметрами и критериями, приведенными в Техническом задании Договора;

в соответствии с требованиями, изложенными в п.3.4. «Требования к управлению событиями» Технического задания Договора, обеспечено оповещение специалистов Исполнителя и Заказчика, и Государственного заказчика о событиях мониторинга программных средств функционирования мониторинга ППО (далее – ПСФМ), фиксация их в программных средствах управления процессами службы технической поддержки (далее – ПСУП), проверка доступности и работоспособности: ГИС Минфина России, служб, сервисов, интеграций между ППО и внешними информационными системами, а также обеспечен контроль параметров назначения ППО;

в соответствии с требованиями, изложенными в п.3.6. «Требования к работе по консультационной и технической поддержке пользователей» Технического задания Договора, обеспечена регистрация, обработка и решение запросов пользователей, служб технической поддержки (далее – СТП), связанных с получением информации и функциями, реализованными в ППО Модуля мер поддержки, а также работоспособностью и управлением функционированием данного ППО;

в соответствии с требованиями, изложенными в п.3.8. «Требования к работе по управлению проблемами и рисками» Технического задания Договора, выполнены мероприятия по:

[list-style-type=dash]
* выявлению и прогнозированию проблем на основе анализа инцидентов;
* диагностике проблем;
* предоставлению временного решения для устранения проблем;
* предоставлению постоянного решения для устранения проблем;
* информированию Заказчика о ходе устранения проблем;
* мониторингу актуальности решения проблемы;
* передаче описания проблем разработчику ППО ГИС Минфина России и предоставление Заказчику полученного ответа * разработчика.

В соответствии с требованиями, изложенными в п.4. «Требования к составу и содержанию документов», подготовлена отчетная документация для Модуля мер поддержки в соответствии с требованиями Технического задания Договора.

Сведения о составе и трудоемкости выполненных работ по сопровождению Модуля мер поддержки приведены в Приложении 1 к настоящему отчету.
